name: vidacoletiva
description: "A new Flutter project."
publish_to: 'none'

version: 2.6.1+43

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  firebase_core: ^3.4.0
  get_it: ^8.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  http: ^1.2.2
  crypto: ^3.0.3
  googleapis: ^14.0.0
  convex_bottom_bar: ^3.2.0
  record: ^6.0.0
  just_audio: ^0.10.4
  path_provider: ^2.1.5
  path: ^1.9.0
  dropdown_button2: ^2.3.9
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/resources/assets/images/logo_white_bg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/resources/assets/images/logo_white_bg.png"
    background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - lib/resources/assets/images/