name: vidacoletiva
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  firebase_core: ^3.4.0
  get_it: ^8.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  http: ^1.2.2
  crypto: ^3.0.3
  googleapis: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/resources/assets/images/