// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jCRtDftnlrRYDPcESXNE8PKqMNy8_Hw',
    appId: '1:231627897335:web:e7f849dc6dd23287e096f2',
    messagingSenderId: '231627897335',
    projectId: 'vida-coletiva-736b4',
    authDomain: 'vida-coletiva-736b4.firebaseapp.com',
    storageBucket: 'vida-coletiva-736b4.appspot.com',
    measurementId: 'G-5R0LK569RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyColhPWf2XP6LiCd8Ptlz5YbqtTs5yDG34',
    appId: '1:231627897335:android:70fec109b453a527e096f2',
    messagingSenderId: '231627897335',
    projectId: 'vida-coletiva-736b4',
    storageBucket: 'vida-coletiva-736b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqz_9WVG1lMshD7P9R6p_qWBDXvU_jt4',
    appId: '1:231627897335:ios:c41689c64e9d2850e096f2',
    messagingSenderId: '231627897335',
    projectId: 'vida-coletiva-736b4',
    storageBucket: 'vida-coletiva-736b4.appspot.com',
    androidClientId: '231627897335-cjv7nj7q0n20ceo05bfugmn7tjg3jksf.apps.googleusercontent.com',
    iosClientId: '231627897335-5fjojncg6cuidnfe5ts80n8cll4qn5u2.apps.googleusercontent.com',
    iosBundleId: 'br.uff.vidacoletiva',
  );

}